apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-config
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/ssd/media/config