apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-data
spec:
  storageClassName: manual
  capacity:
    storage: 1024Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/hdd/media/data