apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: media-data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1024Gi