apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: babybuddy
  name: babybuddy
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"