apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: "64Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd/ollama"