apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ollama
  labels:
    app: ollama
spec:
  selector:
    matchLabels:
      name: ollama
  template:
    metadata:
      labels:
        name: ollama
    spec:
      nodeSelector:
        kubernetes.io/hostname: pimaster
      containers:
        - name: ollama
          image: ollama/ollama:0.5.7
          volumeMounts:
            - mountPath: /root/.ollama
              name: ollama
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:main
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: OLLAMA_BASE_URL
              value: "http://localhost:11434"
            - name: WEBUI_AUTH
              value: "False"
      volumes:
        - name: ollama
          persistentVolumeClaim:
            claimName: ollama
      automountServiceAccountToken: false
