apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ollama
  name: ollama
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "64Gi"